server:
  port: 8002
spring:
  application:
    name: cloud-recommender-service
  data:
    mongodb:
      uri: "172.18.11.107"
      port: 27017
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848,localhost:8849 #配置nacos地址
  management:
    endpoints:
      web:
        exposure:
          include: "*"

