server:
  port: 9527

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: consumer-recommender
          uri: lb://cloud-recommender-consumer
          predicates:
            - Path=/rest/**


    nacos:
      discovery:
        server-addr: localhost:8848 #配置nacos地址

management:
  endpoints:
    web:
      exposure:
        include: "*"