server:
  port: 80
spring:
  application:
    name: cloud-recommender-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #配置nacos地址
management:
  endpoints:
    web:
      exposure:
        include: "*"

ribbon:
  ReadTimeout: 5000
  ConnectionTimeout: 5000